### ISSUE TITLE
Loading default views instead if there is not any global templates

### ISSUE THREAD

**Issue by vpassama** [CanalTP/NmmPortalBundle#29]
Hi,

I succeed installing NMM/Sam. Now I want to log in and check everything is OK with Sam interface.

Potential problems incoming : 

- no (braincrafted)bootstrap / jquery loaded in dependencies (because they're actually declared in MTT but I didn't install it)
- If I don't provide default views in global app/Resources directory (base.html.twig, modal.html.twig, footer.html.twig) I get an exception for missing views.

For the second problem, and because you provide default views in NMM/Sam, we should use [twig extends with dynamism](http://twig.sensiolabs.org/doc/tags/extends.html#dynamic-inheritance) in order to provide a default theme and let the user decide if he wants some customization.

@datanel tell me when you have time to discuss this on IRC.

**Comment by datanel** [comment]
all PRs merged. Thank you
